#############################
# VM-TEST-DEPLOY
#############################

- hosts: vm-test-deploy,blk-poc-01,blk-nillion-kelvin
  become: true
  become_user: root

  roles:
  - { role: node,
      service_name: nillion,
      service_network: nillion-chain-testnet-1,
      tags: [ 'nillion' ] }