---
- name: reload systemd {{ service }}
  systemd:
    daemon_reload: yes

- name: restart docker
  service:
    name: docker
    state: restarted

- name: restart ufw
  service:
    name: ufw
    state: restarted

- name: restart {{ service_systemd_unit }}
  service:
    name: "{{ service_systemd_unit }}"
    state: restarted
