---
#
# Docker
#
- name: 01-docker | import docker's APT signing key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  tags:
    - docker

- name: 01-docker | add Docker's repository ({{ ansible_distribution_release }})
  apt_repository:
    repo: deb [arch={{ linux_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
    filename: docker
    update_cache: yes
  tags:
    - docker

- name: 01-docker | install docker packages
  apt:
    name: [ "ca-certificates", "curl", "gnupg-agent", "software-properties-common", "docker-ce", "docker-ce-cli", "containerd.io" ]
    state: present
    update_cache: yes 
    cache_valid_time: 3600
  ignore_errors: "{{ ansible_check_mode }}"
  notify:
  - reload systemd {{ service }}
  tags:
    - docker

- name: 01-docker | check if docker-compose binary exists
  stat:
    path: "{{ docker_compose_dest }}"
  register: docker_compose_stat
  tags:
    - docker

- name: 01-docker | download docker-compose binary {{ docker_compose_version }}
  get_url:
    mode: 0755
    url: "{{ docker_compose_url }}"
    dest: "{{ docker_compose_dest }}"
    checksum: "{{ docker_compose_checksum }}"
  when: not docker_compose_stat.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - docker

- name: 01-docker | start dockerd
  service:
    name: docker
    state: started
  tags:
    - docker
